blank_issues_enabled: false
issue_templates:
  - name: "Bug Report"
    description: "Report a bug in the project"
    title: "[BUG] <Title>"
    labels: ["triage", "bug"]
    assignees: []

  - name: "Feature Request"
    description: "Request a new feature or enhancement"
    title: "[FEATURE] <Title>"
    labels: ["triage", "enhancement"]
    assignees: []
